# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='id',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='userName',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
